### ISSUE TITLE
feat: add upcoming public transport departures

### ISSUE THREAD

**Issue by ondrejnedoma** [Peperman66/HejPanel#1]
I think that having a small section at the bottom of the screen with the upcoming public transport departures from the Ladova bus stop for one column as well as the Na Trati bus stop + the Olomouc-Hejčín train stop combined for another column would be super useful for many students. I'd be more than happy to work on this over the weekend, implementing it by fetching the departures and delays (for some vehicles) from IDOS. And many thanks to you for making this open-source 🙏

Ondřej Nedoma, IV.B6

**Comment by ondrejnedoma** [comment]
actually now that I've looked closer, this probably isn't the new version of HejPanel 😬 is the new one open-source too?

**Comment by ondrejnedoma** [comment]
Okay well apparently the new version is written in PHP *sigh*

**Comment by Peperman66** [comment]
Hi, this version of HejPanel is no longer being used (since earlier this year). [The new variant](https://github.com/K0stka/HejPanel) is made by a different person. Maybe you could try to post the issue there. Nevertheless, it's still an interesting feature request.
